# .guthub/workflows/app.yaml
name: AWS Test Suite With Pytest
on: push

env:
  AWS_REGION: "us-east-1"
permissions: 
      id-token : write
      contents: read

jobs:
  AWSDeploymenttesting:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credential@v1
        with:
          role-to-asume: arn:aws:iam:398492:role/github-oidc-role
          role-session-name: samplesession
          aws-region: 'us-east-1'
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          oython-version: "3.9"

      - name: Install required python modules
        run: |
          python -m pip install --upgrade boto3 moto pytest

      - name: Run AWS test suite
        working-directory: ./AWSTestExecutions
        run: |
          pytest -v